# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Meteor Tutorials
subtitle:
description: Meteor Tutorials - From Noob to PRO
author: Theodor Diaconu
language: en
timezone:

apis:
  ga: UA-40568040-10
#  docsearch:
#    apiKey: c6162b5842b0dc5f7af8c186fff8f5bb
#    indexName: grapher

sidebar_categories:
  null:
    - index
  'Chapter 1':
    - chapters/1/intro
    - chapters/1/collections
    - chapters/1/methods
    - chapters/1/reactivity
    - chapters/1/pubsub
    - chapters/1/users
    - chapters/1/security
    - chapters/1/meteorSnacks
    - chapters/1/conclusion
  'Chapter 2':
    - chapters/2/intro
    - chapters/2/react
    - chapters/2/css
    - chapters/2/conclusion
  'Chapter 3':
    - chapters/3/intro
    - chapters/3/persistence-layer
    - chapters/3/testing
    - chapters/3/services
    - chapters/3/events
    - chapters/3/methods
    - chapters/3/publications
    - chapters/3/fixtures
    - chapters/3/reusable-modules
    - chapters/3/linting
    - chapters/3/emails
    - chapters/3/microservices
    - chapters/3/structure
    - chapters/3/conclusion

github_repo: 'cult-of-coders/meteor-tuts'
content_root: 'source'

# themeing
favicon: '/images/favicon.png'

logo:
  nav_mobile: '/images/logo.png'
  url: 'http://www.cultofcoders.com'
  title: 'Meteor Tuts'
  subtitle: ''

nav_links:
  Meteor jobs:
    url: https://www.cultofcoders.com
    taget: _new
  Atmosphere:
    url: https://www.atmospherejs.com
    target: _new
  NPM:
    url: https://www.npmjs.com/
    target: _new
  Meteor API:
    url: https://docs.meteor.com/
    target: _new
  Meteor Guide:
    url: https://guide.meteor.com/
    target: _new

social_links:
  github: 'https://github.com/cult-of-coders/meteor-tuts.com'
  twitter: '@culotfcoders'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.meteor-tuts.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: meteor
marked:
  breaks: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: s3
